/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosPrincipal;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vizcarra
 */
public class frmMarca extends javax.swing.JFrame {

    ResultSet rstId = null;
    DefaultTableModel model;
    Connection conn;
    Statement sent;
    String obtenerId = "";
    int obtner_id_marca, mar_ag_mo = 0, saberexiste = 0;

    ;
    /**
     * Creates new form frmMarca
     */
    public frmMarca() {
        setTitle("Marca");
        setResizable(false);
        initComponents();
        ocultarCamposMarca();
        caracteristicasId();
        OpcionesTabla();
    }

    public void OpcionesTabla() {
        int fila = tblMarca.getRowCount();
        if (fila == 0) {
            btnModificarMarca.setEnabled(false);
            btnEliminarMarca.setEnabled(false);
        } else if (fila > 0) {
            btnModificarMarca.setEnabled(true);
            btnEliminarMarca.setEnabled(true);
        }
    }

    public void ocultarCamposMarca() {
        lblRegistrarMarca.setVisible(false);
        lblModificarMarca.setVisible(false);
        lblCodigoMarca.setVisible(false);
        lblNombreMarca.setVisible(false);
        lblDescripcionMarca.setVisible(false);
        txtCodigoMarca.setVisible(false);
        txtNombreMarca.setVisible(false);
        txtDescripcionMarca.setVisible(false);
        btnGuardarMarca.setVisible(false);
        btnCancelarMarca.setVisible(false);
    }

    public void mostrarCamposCategoria() {
        lblCodigoMarca.setVisible(true);
        lblNombreMarca.setVisible(true);
        lblDescripcionMarca.setVisible(true);
        txtCodigoMarca.setVisible(true);
        txtNombreMarca.setVisible(true);
        txtDescripcionMarca.setVisible(true);
        btnGuardarMarca.setVisible(true);
        btnCancelarMarca.setVisible(true);
    }

    public void caracteristicasId() {
        String[] titulomar = {"Id", "Nombre", "Descripcion"};
        model = new DefaultTableModel(null, titulomar);
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM marca");
            String[] fila = new String[3];
            while (rs.next()) {
                fila[0] = rs.getString("Id");
                fila[1] = rs.getString("Nombre");
                fila[2] = rs.getString("Descripcion");
                model.addRow(fila);
            }
            tblMarca.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnSubMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpnBarraSuperior = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarca = new javax.swing.JTable();
        btnRegistrarMarca = new javax.swing.JButton();
        btnModificarMarca = new javax.swing.JButton();
        btnEliminarMarca = new javax.swing.JButton();
        btnCancelarMarca = new javax.swing.JButton();
        btnGuardarMarca = new javax.swing.JButton();
        lblDescripcionMarca = new javax.swing.JLabel();
        txtDescripcionMarca = new javax.swing.JTextField();
        txtCodigoMarca = new javax.swing.JTextField();
        lblNombreMarca = new javax.swing.JLabel();
        lblCodigoMarca = new javax.swing.JLabel();
        txtNombreMarca = new javax.swing.JTextField();
        lblRegistrarMarca = new javax.swing.JLabel();
        lblModificarMarca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marca");
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jpnSubMenu.setBackground(new java.awt.Color(102, 0, 0));
        jpnSubMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnSubMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Home.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jpnSubMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home/Marca.png"))); // NOI18N
        jpnSubMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jpnBarraSuperior.setBackground(new java.awt.Color(0, 0, 0));
        jpnBarraSuperior.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpnBarraSuperior.setMinimumSize(new java.awt.Dimension(1200, 50));
        jpnBarraSuperior.setPreferredSize(new java.awt.Dimension(1200, 50));
        jpnBarraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpnBarraSuperiorMouseDragged(evt);
            }
        });
        jpnBarraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnBarraSuperiorMousePressed(evt);
            }
        });
        jpnBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("Marca");
        lblLogo.setToolTipText("");
        jpnBarraSuperior.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Error.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jpnBarraSuperior.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 50, 50));

        tblMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Nombre", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarca);

        btnRegistrarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/botones/nuevo2.png"))); // NOI18N
        btnRegistrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMarcaActionPerformed(evt);
            }
        });

        btnModificarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/botones/modificar.png"))); // NOI18N
        btnModificarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMarcaActionPerformed(evt);
            }
        });

        btnEliminarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/botones/eliminar.png"))); // NOI18N
        btnEliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMarcaActionPerformed(evt);
            }
        });

        btnCancelarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/botones/cancelar.png"))); // NOI18N
        btnCancelarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMarcaActionPerformed(evt);
            }
        });

        btnGuardarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/botones/guardarprov.png"))); // NOI18N
        btnGuardarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMarcaActionPerformed(evt);
            }
        });

        lblDescripcionMarca.setText("Descripción");

        txtCodigoMarca.setEnabled(false);
        txtCodigoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoMarcaActionPerformed(evt);
            }
        });

        lblNombreMarca.setText("Nombre:");

        lblCodigoMarca.setText("Código:");

        lblRegistrarMarca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRegistrarMarca.setText("Registrar Marca");

        lblModificarMarca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblModificarMarca.setText("Modificar Marca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnModificarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnEliminarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDescripcionMarca)
                                .addGap(45, 45, 45)
                                .addComponent(txtDescripcionMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreMarca)
                                    .addComponent(lblCodigoMarca))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblModificarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpnBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnSubMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblRegistrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblModificarMarca)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigoMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreMarca)
                            .addComponent(txtNombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDescripcionMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcionMarca))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(355, 355, 355))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpnBarraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnBarraSuperiorMouseDragged

    }//GEN-LAST:event_jpnBarraSuperiorMouseDragged

    private void jpnBarraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnBarraSuperiorMousePressed

    }//GEN-LAST:event_jpnBarraSuperiorMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        frmHome home = new frmHome();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnRegistrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMarcaActionPerformed
        mar_ag_mo = 1;
        lblRegistrarMarca.setVisible(true);
        mostrarCamposCategoria();
        obtner_id_marca = 0;
        Conexion cc = new Conexion();
        Connection cn = cc.getConnection();
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(Id) FROM marca");
            while (rs.next()) {
                obtenerId = rs.getString(1);
                String solution = "" + rs.getString(1);
                if (solution.equals("null")) {
                    obtenerId = "0";
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        obtner_id_marca = Integer.parseInt(obtenerId) + 1;
        txtCodigoMarca.setText("" + obtner_id_marca);
        btnRegistrarMarca.setEnabled(false);
        btnModificarMarca.setEnabled(false);
        btnEliminarMarca.setEnabled(false);
        txtNombreMarca.setText("");
        txtDescripcionMarca.setText("");
    }//GEN-LAST:event_btnRegistrarMarcaActionPerformed

    private void btnCancelarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMarcaActionPerformed
        ocultarCamposMarca();
        btnRegistrarMarca.setEnabled(true);
        OpcionesTabla();
        txtCodigoMarca.setText("");
    }//GEN-LAST:event_btnCancelarMarcaActionPerformed

    private void btnGuardarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMarcaActionPerformed
        if (txtNombreMarca.getText().equals("") || txtDescripcionMarca.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar los campos");
        } else {
            Conexion cc = new Conexion();
            Connection cn = cc.getConnection();
            String Id, Nombre, Descripcion;
//////////////////////////////agregar///////////////////////
            if (mar_ag_mo == 1) {
                for (int i = 0; i < tblMarca.getRowCount(); i++) {
                    if (txtNombreMarca.getText().equals(tblMarca.getValueAt(i, 1).toString())) {
                        saberexiste = 1;
                    }
                }
                if (saberexiste == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Marca Existente /n Realice de nuevo el proceso");
                } else {
                    obtner_id_marca = obtner_id_marca + 1;
                    String sql = "";
                    Id = txtCodigoMarca.getText();
                    Nombre = txtNombreMarca.getText();
                    Descripcion = txtDescripcionMarca.getText();
                    try {
                        PreparedStatement psd = cn.prepareStatement("INSERT INTO marca(Id,Nombre,Descripcion) VALUES (?,?,?)");
                        psd.setString(1, Id);
                        psd.setString(2, Nombre);
                        psd.setString(3, Descripcion);
                        int n = psd.executeUpdate();
                        if (n > 0) {
                            JOptionPane.showMessageDialog(null, "Nueva Marca Registrado!", "CORRECTO", JOptionPane.PLAIN_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Su Marca No Se Guardo ", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ErrorTienda) {
                        JOptionPane.showMessageDialog(this, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    txtCodigoMarca.setText("" + obtner_id_marca);
                    txtNombreMarca.setText("");
                    txtDescripcionMarca.setText("");
                    caracteristicasId();
                }
                // Para Modificar  
            } else if (mar_ag_mo == 2) {
                int saberdm = 0, sabenm = 0;
                String idMarcaIgual = "0";
                for (int i = 0; i < tblMarca.getRowCount(); i++) {
                    if (txtNombreMarca.getText().equals(tblMarca.getValueAt(i, 1).toString())) {
                        sabenm = 1;
                        idMarcaIgual = tblMarca.getValueAt(i, 0).toString();
                        if (txtDescripcionMarca.getText().equals(tblMarca.getValueAt(i, 2).toString())) {
                            saberdm = 1;
                        }
                        if (sabenm == 1 && saberdm == 1) {
                            JOptionPane.showMessageDialog(rootPane, "Los campos siguen igual, debe modificar almenos un campo");
                            idMarcaIgual = "0";
                            break;
                        } else {
                            sabenm = 0;
                            saberdm = 0;
                        }
                    }
                }
                if (!idMarcaIgual.equals(txtCodigoMarca.getText()) && !idMarcaIgual.equals("0")) {
                    JOptionPane.showMessageDialog(rootPane, "No se modifico, esa marca ya existe");
                } else if (!(sabenm == 1 && saberdm == 1) || idMarcaIgual.equals(txtCodigoMarca.getText())) {
                    int Idmm;
                    Id = txtCodigoMarca.getText();
                    Idmm = Integer.parseInt(txtCodigoMarca.getText());
                    Nombre = txtNombreMarca.getText();
                    Descripcion = txtDescripcionMarca.getText();
                    String insertarmm = "UPDATE marca SET Id=?, Nombre=?, Descripcion=? WHERE Id='" + Idmm + "'";
                    try {
                        PreparedStatement psd = cn.prepareStatement(insertarmm);
                        psd.setString(1, Id);
                        psd.setString(2, Nombre);
                        psd.setString(3, Descripcion);
                        int n = psd.executeUpdate();
                        if (n > 0) {
                            JOptionPane.showMessageDialog(null, "Marca modificada!", "CORRECTO", JOptionPane.PLAIN_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Marca no modificada ", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ErrorTienda) {
                        JOptionPane.showMessageDialog(this, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    int seleccion = tblMarca.getSelectedRow();
                    String nomta = (tblMarca.getValueAt(seleccion, 1).toString());
                    if (txtNombreMarca.getText().equals(tblMarca.getValueAt(seleccion, 1).toString())) {
                    } else {
                        try {
                            PreparedStatement psd = cn.prepareStatement("UPDATE productos SET Marca=? WHERE Marca='" + Nombre + "'");
                            psd.setString(1, Nombre);
                            int n = psd.executeUpdate();
                        } catch (SQLException ErrorTienda) {
                            JOptionPane.showMessageDialog(this, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    ocultarCamposMarca();
                    btnRegistrarMarca.setEnabled(true);
                    btnModificarMarca.setEnabled(true);
                    btnEliminarMarca.setEnabled(true);
                    caracteristicasId();
                }//cerrar el else de la comparacion del if si los campos no se modifican
            }//cierra modificar
        }// cierra else si estan los campos llenos
    }//GEN-LAST:event_btnGuardarMarcaActionPerformed

    private void btnModificarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMarcaActionPerformed
        if (tblMarca.getSelectedRow() != -1) {
            mar_ag_mo = 2;
            lblModificarMarca.setVisible(true);
            mostrarCamposCategoria();
            btnRegistrarMarca.setEnabled(false);
            btnModificarMarca.setEnabled(false);
            btnEliminarMarca.setEnabled(false);
            if (tblMarca.getSelectedRow() != -1) {
                int seleccion = tblMarca.getSelectedRow();
                txtCodigoMarca.setText(tblMarca.getValueAt(seleccion, 0).toString());
                txtNombreMarca.setText((tblMarca.getValueAt(seleccion, 1).toString()));
                txtDescripcionMarca.setText((tblMarca.getValueAt(seleccion, 2).toString()));
                txtNombreMarca.requestFocus();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Seleccione una marca");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una una marca");
        }
    }//GEN-LAST:event_btnModificarMarcaActionPerformed

    private void txtCodigoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMarcaActionPerformed

    private void btnEliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMarcaActionPerformed
        if (tblMarca.getSelectedRow() != -1) {
            int fila = tblMarca.getSelectedRow();
            String valor = tblMarca.getValueAt(fila, 0).toString();
            String marcausada = tblMarca.getValueAt(fila, 1).toString();
            if (fila >= 0) {
                Conexion cc = new Conexion();
                Connection cn = cc.getConnection();
                String sabervaor = "SELECT COUNT(*) FROM productos WHERE Marca='" + marcausada + "'";
                try {
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(sabervaor);
                    while (rs.next()) {
                        marcausada = rs.getString(1);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(frmMarca.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (marcausada.equals("0")) {
                    try {
                        int a = JOptionPane.showConfirmDialog(this, "¿Esta Seguro?");
                        if (a == JOptionPane.YES_OPTION) {
                            PreparedStatement pps = cn.prepareStatement("DELETE FROM marca WHERE Id='" + valor + "'");
                            pps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "El Equipo Se Ha Eliminado!", "CONFIRMACION", JOptionPane.PLAIN_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(frmMarca.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    caracteristicasId();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "No se puede eliminar por que hay existencias");
                }
            }
            OpcionesTabla();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una Marca");
        }
    }//GEN-LAST:event_btnEliminarMarcaActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarMarca;
    private javax.swing.JButton btnEliminarMarca;
    private javax.swing.JButton btnGuardarMarca;
    private javax.swing.JButton btnModificarMarca;
    private javax.swing.JButton btnRegistrarMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnBarraSuperior;
    private javax.swing.JPanel jpnSubMenu;
    private javax.swing.JLabel lblCodigoMarca;
    private javax.swing.JLabel lblDescripcionMarca;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblModificarMarca;
    private javax.swing.JLabel lblNombreMarca;
    private javax.swing.JLabel lblRegistrarMarca;
    private javax.swing.JTable tblMarca;
    private javax.swing.JTextField txtCodigoMarca;
    private javax.swing.JTextField txtDescripcionMarca;
    private javax.swing.JTextField txtNombreMarca;
    // End of variables declaration//GEN-END:variables
}
